# Generated by Django 5.1.1 on 2024-10-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
