# Generated by Django 5.1.1 on 2024-09-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_itemtag_item_is_sold_item_item_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True),
        ),
    ]
