# Generated by Django 5.1.1 on 2024-09-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_item_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtag',
            name='tag_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
