# Generated by Django 5.1.1 on 2024-10-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_item_quantity'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='base.itemtag'),
        ),
    ]
