# Generated by Django 5.1.1 on 2024-09-24 03:21

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='current_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='time_up',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 3, 26, 30, 956170, tzinfo=datetime.timezone.utc)),
        ),
    ]
