# Generated by Django 5.1.1 on 2024-09-24 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_onetimepassword_time_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='time_up',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 23, 45, 23, 703480, tzinfo=datetime.timezone.utc)),
        ),
    ]
