# Generated by Django 5.1.1 on 2024-10-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='business_name',
            new_name='first_name',
        ),
    ]
