# Generated by Django 5.1.1 on 2024-09-24 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_onetimepassword_used_alter_onetimepassword_time_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimepassword',
            old_name='used',
            new_name='is_used',
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='time_up',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 23, 46, 39, 823769, tzinfo=datetime.timezone.utc)),
        ),
    ]
