# Generated by Django 5.1.1 on 2024-09-25 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_used_onetimepassword_is_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='onetimepassword',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='time_up',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 0, 3, 31, 27554, tzinfo=datetime.timezone.utc)),
        ),
    ]
