# Generated by Django 5.1.1 on 2024-09-25 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_onetimepassword_time_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='time_up',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 0, 41, 12, 122594, tzinfo=datetime.timezone.utc)),
        ),
    ]
