# Generated by Django 5.1.1 on 2024-09-25 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_onetimepassword_time_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='time_up',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='time_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 0, 43, 23, 996538, tzinfo=datetime.timezone.utc)),
        ),
    ]
