# Generated by Django 5.1.1 on 2024-10-03 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_onetimepassword_time_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='time_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 6, 12, 28, 666662, tzinfo=datetime.timezone.utc)),
        ),
    ]
