# Generated by Django 5.1.1 on 2024-10-04 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_onetimepassword_time_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='time_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 5, 6, 36, 673053, tzinfo=datetime.timezone.utc)),
        ),
    ]
