# Generated by Django 5.1.1 on 2024-10-05 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_onetimepassword_time_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='time_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 6, 57, 56, 724033, tzinfo=datetime.timezone.utc)),
        ),
    ]
